import test from "node:test";
import assert from "node:assert/strict";
import { applyMove, BLACK, createInitialState, getWinningLine, indexOf, stateFromMoves, validateState, WHITE } from "../src/games/gomoku/rules.js";
import { chooseGomokuPracticeMove } from "../src/games/gomoku/practice-ai.js";

function boardWith(stones){const board=Array(225).fill(null);for(const [r,c,s] of stones)board[indexOf(r,c)]=s;return board;}
test("creates a valid 15 by 15 casual Gomoku board",()=>{const game=createInitialState();assert.equal(game.board.length,225);assert.equal(game.currentTurn,BLACK);assert.ok(validateState(game));});
test("rejects occupied and out-of-range intersections",()=>{const game=applyMove(createInitialState(),7,7);assert.throws(()=>applyMove({...game,currentTurn:BLACK},7,7),/occupied/);assert.throws(()=>applyMove(createInitialState(),15,0),/Invalid/);});
test("detects horizontal vertical and both diagonal wins including edges",()=>{for(const stones of [Array.from({length:5},(_,i)=>[0,i,BLACK]),Array.from({length:5},(_,i)=>[i,14,BLACK]),Array.from({length:5},(_,i)=>[i,i,BLACK]),Array.from({length:5},(_,i)=>[i,14-i,BLACK])]){const line=getWinningLine(boardWith(stones),stones[4][0],stones[4][1],BLACK);assert.equal(line.length,5);}});
test("returns the complete six-stone winning run",()=>{const stones=Array.from({length:6},(_,i)=>[8,i+3,WHITE]);assert.equal(getWinningLine(boardWith(stones),8,5,WHITE).length,6);});
test("gaps and opponent stones block a line",()=>{assert.equal(getWinningLine(boardWith([[2,2,BLACK],[2,3,BLACK],[2,5,BLACK],[2,6,BLACK],[2,7,BLACK]]),2,7,BLACK).length,0);assert.equal(getWinningLine(boardWith([[3,1,BLACK],[3,2,BLACK],[3,3,WHITE],[3,4,BLACK],[3,5,BLACK]]),3,5,BLACK).length,0);});
test("reconstructs immutable moves with Black first",()=>{const state=stateFromMoves([{moveNumber:1,row:7,column:7,stone:BLACK},{moveNumber:2,row:7,column:8,stone:WHITE}]);assert.equal(state.moveCount,2);assert.equal(state.currentTurn,BLACK);});
test("a full board without five stones ends in a draw",()=>{const board=Array.from({length:225},(_,index)=>((Math.floor(index/15)+Math.floor((index%15)/2))%2?BLACK:WHITE)),row=14,column=14,stone=board[indexOf(row,column)];board[indexOf(row,column)]=null;const result=applyMove({...createInitialState(stone),board,moveCount:224},row,column);assert.equal(result.status,"draw");assert.equal(result.winner,null);});
test("Gomoku AI chooses legal nearby moves and wins or blocks at medium-high levels",()=>{let state=createInitialState();state=applyMove(state,7,7);const low=chooseGomokuPracticeMove(state,1,()=>0);assert.equal(state.board[indexOf(low.row,low.column)],null);const winBoard=boardWith([[5,3,WHITE],[5,4,WHITE],[5,5,WHITE],[5,6,WHITE]]);const winState={...createInitialState(WHITE),board:winBoard,moveCount:4};assert.deepEqual(chooseGomokuPracticeMove(winState,6,()=>0),{row:5,column:2});const threatBoard=boardWith([[9,3,BLACK],[9,4,BLACK],[9,5,BLACK],[9,6,BLACK]]);const blockState={...createInitialState(WHITE),board:threatBoard,moveCount:4};assert.deepEqual(chooseGomokuPracticeMove(blockState,6,()=>0),{row:9,column:2});});
test("rules and AI are pure modules",async()=>{const fs=await import("node:fs/promises");for(const file of ["src/games/gomoku/rules.js","src/games/gomoku/practice-ai.js"]){const source=await fs.readFile(file,"utf8");assert.doesNotMatch(source,/\b(?:window|document|firebase|Firestore)\b/);}});
